services:
  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: grafana
    ports:
      - 4000:3000
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:4000/
      - GF_PLUGINS_PREINSTALL=grafana-clock-panel
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
    restart: unless-stopped
    networks:
      - monitoring

volumes:
  grafana-storage:

networks:
  monitoring:
    external: true
    name: ser_prometheus_monitoring
