{
 "title": "Airflow",
 "description": "Basic airflow dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "DAG Paused",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "airflow_dag_paused", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DAG Run State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "airflow_dag_run_state", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active DAG",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "airflow_dag_active", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Event Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "airflow_event_total", "legendFormat": "__auto" }
   ]
  }
 ]
}